server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Vite build ra SPA: moi duong dan deu tra ve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|svg|png|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
